spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.125.119:3306/myblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jx@19940228
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true


logging:
  level:
    root: warn
    com.jipinxiaohei.myblog: info
  file: log/blog-pro.log
server:
  port: 443
  ssl:
    key-store: 2238324_www.jipinxiaohei.com.pfx
    key-store-password: e60nxbfF
    key-store-type: PKCS12
    enabled: true

